name: skroutz-haskell-api
version: 0.1.0.0
synopsis: Skroutz.gr HTTP API bindings.
description: See README.md
github: ariskou/skroutz-haskell-api
homepage: http://github.com/ariskou/skroutz-haskell-api#readme
bug-reports: https://github.com/ariskou/skroutz-haskell-api/issues
license: Apache-2.0
license-file: LICENSE
author: Remous-Aris Koutsiamanis
maintainer: Remous-Aris Koutsiamanis <ariskou@gmail.com>
copyright: Copyright 2016 Remous-Aris Koutsiamanis
stability: alpha
category: Web

extra-source-files:
  - README.md
  - changelog.md
  - test/fixtures/*/*.json


ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - lens
  - lens-aeson
  - network-uri
  - template-haskell
  - bytestring
  - deepseq
  - transformers
  - either
  - servant
  - servant-client
  - http-client
  - http-client-tls
  - wreq
  - rest-core
  - rest-gen
  - rest-types
  - rest-client
  - rest-stringmap
  - resourcet
  - http-api-data
  - http-conduit
  - http-types
  - containers

library:
  source-dirs: src
  other-modules:
    - Web.Skroutz.Types
    - Web.Skroutz.Types.Base
    - Web.Skroutz.Types.Base.Category
    - Web.Skroutz.Types.Base.FilterGroup
    - Web.Skroutz.Types.Base.Manufacturer
    - Web.Skroutz.Types.Base.Product
    - Web.Skroutz.Types.Base.Shop
    - Web.Skroutz.Types.Base.ShopPaymentMethods
    - Web.Skroutz.Types.Base.ShopShipping
    - Web.Skroutz.Types.Base.ShopLocation
    - Web.Skroutz.Types.Base.ShopLocationAddress
    - Web.Skroutz.Types.Base.ShopReview
    - Web.Skroutz.Types.Base.Sku
    - Web.Skroutz.Types.Base.SkuImages
    - Web.Skroutz.Types.Base.SkuReview
    - Web.Skroutz.Types.Base.SkuSpecification
    - Web.Skroutz.Types.Base.SkuPrice
    - Web.Skroutz.Types.Base.Token
    - Web.Skroutz.Types.Base.URI
    - Web.Skroutz.Types.Base.User
    - Web.Skroutz.Types.Base.Flag
    - Web.Skroutz.Types.ResultWrappers
    - Web.Skroutz.Types.ResultWrappers.Alternative
    - Web.Skroutz.Types.ResultWrappers.GeneralSearchResult
    - Web.Skroutz.Types.ResultWrappers.AppliedFilters
    - Web.Skroutz.Types.ResultWrappers.AvailableFilters
    - Web.Skroutz.Types.ResultWrappers.Autocomplete
    - Web.Skroutz.Types.ResultWrappers.Category
    - Web.Skroutz.Types.ResultWrappers.FilterGroup
    - Web.Skroutz.Types.ResultWrappers.Manufacturer
    - Web.Skroutz.Types.ResultWrappers.Meta
    - Web.Skroutz.Types.ResultWrappers.Pagination
    - Web.Skroutz.Types.ResultWrappers.Product
    - Web.Skroutz.Types.ResultWrappers.Shop
    - Web.Skroutz.Types.ResultWrappers.ShopLocation
    - Web.Skroutz.Types.ResultWrappers.ShopReview
    - Web.Skroutz.Types.ResultWrappers.Sku
    - Web.Skroutz.Types.ResultWrappers.SkuReview
    - Web.Skroutz.Types.ResultWrappers.SkuSpecification
    - Web.Skroutz.Types.ResultWrappers.SkuPrice
    - Web.Skroutz.Types.ResultWrappers.StrongMatches
    - Web.Skroutz.Types.ResultWrappers.Flag
    - Web.Skroutz.Types.ResultWrappers.User
    - Web.Skroutz.TH
    - Web.Skroutz.Endpoints
    - Web.Skroutz.Endpoints.Auth
    - Web.Skroutz.Endpoints.Types
    - Web.Skroutz.Endpoints.Types.Common
    - Web.Skroutz.Endpoints.Types.Category
    - Web.Skroutz.Endpoints.Types.Manufacturer
    - Web.Skroutz.Endpoints.Types.Sku
    - Web.Skroutz.Endpoints.Types.Product
    - Web.Skroutz.Endpoints.Types.Shop
    - Web.Skroutz.Endpoints.Types.ShopLocation
    - Web.Skroutz.Endpoints.Types.ShopReview
    - Web.Skroutz.Endpoints.Types.FilterGroup
    - Web.Skroutz.Endpoints.Types.Flag
    - Web.Skroutz.Endpoints.Types.User
  exposed-modules:
    - Web.Skroutz

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - Web.Skroutz.Common
      - Web.Skroutz.Types.CategorySpec
      - Web.Skroutz.Types.ManufacturerSpec
      - Web.Skroutz.Types.ProductSpec
      - Web.Skroutz.Types.ShopSpec
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - skroutz-haskell-api
      - bytestring
      - filepath
      - directory
      - hspec
