name: skroutz-haskell-api
version: 0.1.0.0
synopsis: Skroutz.gr HTTP API bindings.
description: See README.md
github: ariskou/skroutz-haskell-api
homepage: http://github.com/ariskou/skroutz-haskell-api#readme
bug-reports: https://github.com/ariskou/skroutz-haskell-api/issues
license: Apache-2.0
license-file: LICENSE
author: Remous-Aris Koutsiamanis
maintainer: Remous-Aris Koutsiamanis <ariskou@gmail.com>
copyright: Copyright 2016 Remous-Aris Koutsiamanis
stability: alpha
category: Web

extra-source-files:
  - README.md
  - changelog.md
  - test/fixtures/*/*.json


ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - lens
  - lens-aeson
  - network-uri
  - template-haskell
  - bytestring
  - deepseq
  - transformers
  - either
  - servant
  - servant-client
  - http-client
  - http-client-tls

library:
  source-dirs: src
  other-modules:
    - Web.Skroutz.Types
    - Web.Skroutz.Types.AnySearchResult
    - Web.Skroutz.Types.Category
    - Web.Skroutz.Types.Manufacturer
    - Web.Skroutz.Types.Meta
    - Web.Skroutz.Types.Pagination
    - Web.Skroutz.Types.Product
    - Web.Skroutz.Types.Shop
    - Web.Skroutz.Types.ShopPaymentMethods
    - Web.Skroutz.Types.ShopShipping
    - Web.Skroutz.Types.ShopLocation
    - Web.Skroutz.Types.ShopReview
    - Web.Skroutz.Types.SKU
    - Web.Skroutz.Types.SKUReview
    - Web.Skroutz.Types.Token
    - Web.Skroutz.Types.URI
    - Web.Skroutz.TH
    - Web.Skroutz.Endpoints
    - Web.Skroutz.Endpoints.Auth
    - Web.Skroutz.Endpoints.Data
  exposed-modules:
    - Web.Skroutz

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - Web.Skroutz.Common
      - Web.Skroutz.Types.CategorySpec
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - skroutz-haskell-api
      - bytestring
      - filepath
      - directory
      - hspec
